{{- if .Values.namespaceCreate.enabled }}
{{- $namespaceLabels := dict -}}
{{- $_ := set $namespaceLabels "katib.kubeflow.org/metrics-collector-injection" "enabled" -}}
{{- if .Values.podSecurityStandards.enforced -}}
{{- $_ := set $namespaceLabels "pod-security.kubernetes.io/enforce" "restricted" -}}
{{- $_ := set $namespaceLabels "pod-security.kubernetes.io/audit" "restricted" -}}
{{- $_ := set $namespaceLabels "pod-security.kubernetes.io/warn" "restricted" -}}
{{- end -}}
{{- with .Values.namespaceCreate.labels -}}
{{- range $key, $value := . -}}
{{- $_ := set $namespaceLabels $key $value -}}
{{- end -}}
{{- end -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "katib.namespace" . }}
  labels:
    {{- include "katib.labels" . | nindent 4 }}
    {{- toYaml $namespaceLabels | nindent 4 }}
  {{- with .Values.namespaceCreate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
