apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../upstream/env/cert-manager/platform-agnostic-multi-user-k8s-native
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ml-pipeline
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ml-pipeline
    spec:
      template:
        metadata:
          annotations:
            # The Kubernetes API server calls the webhook with its own TLS.
            traffic.sidecar.istio.io/excludeInboundPorts: "8443"
