apiVersion: v2
name: knative-serving
description: Knative Serving with Kubeflow Istio integration
version: 0.1.0
appVersion: "1.23.0"
home: https://github.com/kubeflow/community-distribution
sources:
  - https://github.com/kubeflow/community-distribution/tree/master/common/knative
  - https://github.com/knative/serving
  - https://github.com/knative-extensions/net-istio
annotations:
  licenses: Apache-2.0
  kubeflow.org/queue-proxy-image: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:a3cc71ce80dbc6df8781f15eac2cf3531a4c9815271799afd8776bef9e6aeaf2
