credentials:
  clientSecret: not-a-real-client-secret
  cookieSecret: not-a-real-cookie-secret-00000

istioExternalAuth:
  enabled: true

m2m:
  enabled: true
  issuer: https://kubernetes.default.svc.cluster.local
  jwksUri: http://cluster-jwks-proxy.istio-system.svc.cluster.local/openid/v1/jwks
  additionalJwtRules:
  - issuer: https://kubernetes.default.svc
    jwksUri: http://cluster-jwks-proxy.istio-system.svc.cluster.local/openid/v1/jwks

clusterJwksProxy:
  enabled: true
  image: docker.io/bitnamisecure/kubectl:latest

parameters:
  allowSelfSignedIssuer: "true"
