{{- if .Values.dex.enabled }}
apiVersion: v1
data:
  OIDC_CLIENT_ID: {{ .Values.oidcClient.id | b64enc }}
  OIDC_CLIENT_SECRET: {{ .Values.oidcClient.secret | b64enc }}
kind: Secret
metadata:
  name: dex-oidc-client
  namespace: auth
type: Opaque
{{- end }}
