#!/usr/bin/env python3

import argparse
import copy
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile
import uuid

from collections.abc import Mapping
from pathlib import Path

from ruamel.yaml import YAML

KUSTOMIZE_PATH = Path("applications/dashboard/helm/kustomize")
OUTPUT_PATH = Path("applications/dashboard/helm/manifests")
CRD_KIND = "CustomResourceDefinition"
CRD_RETENTION_ANNOTATION = "helm.sh/resource-policy"
GENERATED_HEADER = (
    "# Code generated by scripts/generate-dashboard-helm-manifests.py. "
    "DO NOT EDIT.\n"
    "# Source: kustomize build applications/dashboard/helm/kustomize\n"
    "# Regenerate with: KUBEFLOW_SYNCHRONIZE_NO_COMMIT=true "
    "./scripts/synchronize-dashboard-manifests.sh\n"
)

COMPONENT_APPLICATION_NAMES = {
    "central-dashboard": "centraldashboard",
    "poddefaults-webhook": "poddefaults-webhook",
    "profile-controller": "profile-controller",
}

# Kustomize appends content hashes to these generated ConfigMap names. Prefix
# fallbacks are scoped by API version, kind, and namespace to avoid classifying
# an unrelated object that happens to share a prefix.
COMPONENT_GENERATED_RESOURCE_PREFIXES = {
    "central-dashboard": (("v1", "ConfigMap", "kubeflow", "dashboard-parameters-"),),
    "poddefaults-webhook": (),
    "profile-controller": (
        ("v1", "ConfigMap", "kubeflow", "profiles-config-"),
        ("v1", "ConfigMap", "kubeflow", "profiles-namespace-labels-data-"),
    ),
}

PAYLOAD_FILENAMES = {
    ("central-dashboard", "resources"): "central-dashboard-resources.yaml",
    ("poddefaults-webhook", "crds"): "poddefaults-webhook-crds.yaml",
    ("poddefaults-webhook", "resources"): "poddefaults-webhook-resources.yaml",
    ("profile-controller", "crds"): "profile-controller-crds.yaml",
    ("profile-controller", "resources"): "profile-controller-resources.yaml",
}


def resource_identity(resource):
    if not isinstance(resource, Mapping):
        raise ValueError("resource identity requires a YAML mapping")

    api_version = resource.get("apiVersion")
    kind = resource.get("kind")
    metadata = resource.get("metadata")
    if not isinstance(api_version, str) or not api_version:
        raise ValueError("resource identity is missing apiVersion")
    if not isinstance(kind, str) or not kind:
        raise ValueError("resource identity is missing kind")
    if not isinstance(metadata, Mapping):
        raise ValueError("resource identity is missing metadata")

    name = metadata.get("name")
    namespace = metadata.get("namespace", "")
    if not isinstance(name, str) or not name:
        raise ValueError("resource identity is missing metadata.name")
    if not isinstance(namespace, str):
        raise ValueError("resource identity has a non-string metadata.namespace")

    return api_version, kind, namespace, name


def kubernetes_object_identity(resource):
    api_version, kind, namespace, name = resource_identity(resource)
    api_group = api_version.split("/", maxsplit=1)[0] if "/" in api_version else ""
    return api_group, kind, namespace, name


def classify_resource(resource):
    identity = resource_identity(resource)
    metadata = resource["metadata"]
    labels = metadata.get("labels", {})
    if labels is None:
        labels = {}
    if not isinstance(labels, Mapping):
        raise ValueError(f"resource {identity} has non-mapping metadata.labels")

    application_label = "app.kubernetes.io/name"
    application_name = labels.get(application_label)
    resource_name = identity[3]
    label_component = None
    if application_label in labels:
        matching_labels = [
            component
            for component, expected_name in COMPONENT_APPLICATION_NAMES.items()
            if application_name == expected_name
        ]
        if not matching_labels:
            raise ValueError(
                f"resource {identity} has unknown application label: "
                f"{application_name!r}"
            )
        label_component = matching_labels[0]

    prefix_components = []
    for component in COMPONENT_APPLICATION_NAMES:
        matches_prefix = any(
            identity[:3] == prefix_identity[:3]
            and re.fullmatch(
                re.escape(prefix_identity[3]) + r"[a-z0-9]{10}",
                resource_name,
            )
            for prefix_identity in COMPONENT_GENERATED_RESOURCE_PREFIXES[component]
        )
        if matches_prefix:
            prefix_components.append(component)

    matching_components = set(prefix_components)
    if label_component is not None:
        matching_components.add(label_component)

    if not matching_components:
        raise ValueError(f"resource {identity} does not match any component")
    if len(matching_components) > 1:
        raise ValueError(
            f"resource {identity} matches multiple components: "
            f"{', '.join(sorted(matching_components))}"
        )
    return matching_components.pop()


def parse_resources(rendered_yaml):
    yaml = YAML()
    yaml.allow_duplicate_keys = False
    resources = []
    for document_number, resource in enumerate(yaml.load_all(rendered_yaml), start=1):
        if resource is None:
            continue
        if not isinstance(resource, Mapping):
            raise ValueError(
                f"YAML document {document_number} is not a Kubernetes resource mapping"
            )
        resources.append(resource)
    if not resources:
        raise ValueError("Kustomize rendered no Kubernetes resources")
    return resources


def add_crd_retention(resource):
    retained_resource = copy.deepcopy(resource)
    metadata = retained_resource["metadata"]
    annotations = metadata.get("annotations")
    if annotations is None:
        annotations = {}
        metadata["annotations"] = annotations
    if not isinstance(annotations, Mapping):
        raise ValueError(
            f"CRD {resource_identity(resource)} has non-mapping metadata.annotations"
        )
    annotations[CRD_RETENTION_ANNOTATION] = "keep"
    return retained_resource


def render_payload(resources):
    yaml = YAML()
    yaml.default_flow_style = False
    yaml.explicit_start = True
    yaml.width = 4096
    stream = io.StringIO()
    yaml.dump_all(resources, stream)
    return GENERATED_HEADER + stream.getvalue()


def generate_payload_contents(resources):
    resources_by_payload = {filename: [] for filename in PAYLOAD_FILENAMES.values()}
    object_identities = set()

    for resource in resources:
        identity = resource_identity(resource)
        object_identity = kubernetes_object_identity(resource)
        if object_identity in object_identities:
            raise ValueError(f"duplicate resource identity: {identity}")
        object_identities.add(object_identity)

        component = classify_resource(resource)
        payload_type = "crds" if resource["kind"] == CRD_KIND else "resources"
        payload_filename = PAYLOAD_FILENAMES.get((component, payload_type))
        if payload_filename is None:
            raise ValueError(
                f"resource {identity} has no payload for {component}/{payload_type}"
            )

        output_resource = (
            add_crd_retention(resource)
            if payload_type == "crds"
            else copy.deepcopy(resource)
        )
        resources_by_payload[payload_filename].append(output_resource)

    empty_payloads = [
        filename
        for filename, payload_resources in resources_by_payload.items()
        if not payload_resources
    ]
    if empty_payloads:
        raise ValueError(
            "required generated payloads are empty: " + ", ".join(empty_payloads)
        )

    return {
        filename: render_payload(payload_resources)
        for filename, payload_resources in resources_by_payload.items()
    }


def write_payloads_atomically(output_directory, payloads):
    output_directory = Path(output_directory)
    output_directory.parent.mkdir(parents=True, exist_ok=True)
    staging_directory = Path(
        tempfile.mkdtemp(
            prefix=f".{output_directory.name}.new-",
            dir=output_directory.parent,
        )
    )
    backup_directory = output_directory.parent / (
        f".{output_directory.name}.old-{uuid.uuid4().hex}"
    )
    previous_directory_moved = False

    try:
        for filename, contents in payloads.items():
            if Path(filename).name != filename:
                raise ValueError(f"payload filename must be a basename: {filename}")
            if not contents.strip():
                raise ValueError(f"generated payload is empty: {filename}")
            (staging_directory / filename).write_text(
                contents,
                encoding="utf-8",
                newline="\n",
            )

        if output_directory.exists():
            os.replace(output_directory, backup_directory)
            previous_directory_moved = True

        try:
            os.replace(staging_directory, output_directory)
        except Exception:
            if previous_directory_moved:
                os.replace(backup_directory, output_directory)
                previous_directory_moved = False
            raise

        if previous_directory_moved:
            shutil.rmtree(backup_directory)
            previous_directory_moved = False
    finally:
        if staging_directory.exists():
            shutil.rmtree(staging_directory)
        if previous_directory_moved and backup_directory.exists():
            if not output_directory.exists():
                os.replace(backup_directory, output_directory)


def generate_dashboard_manifests(repository_root):
    repository_root = Path(repository_root).resolve()
    result = subprocess.run(
        ["kustomize", "build", str(KUSTOMIZE_PATH)],
        cwd=repository_root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "Dashboard Kustomize build failed:\n" + result.stderr.rstrip()
        )

    resources = parse_resources(result.stdout)
    payloads = generate_payload_contents(resources)
    write_payloads_atomically(repository_root / OUTPUT_PATH, payloads)
    return len(resources), tuple(payloads)


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Generate component payloads for the Kubeflow Dashboard Helm chart."
    )
    parser.add_argument(
        "--repository-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Path to the kubeflow/community-distribution repository.",
    )
    return parser.parse_args()


def main():
    arguments = parse_arguments()
    try:
        resource_count, payload_filenames = generate_dashboard_manifests(
            arguments.repository_root
        )
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print(
        f"Generated {resource_count} Dashboard resources across "
        f"{len(payload_filenames)} payloads."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
