#!/usr/bin/env python3

import argparse
import copy
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile
import uuid

from collections.abc import Mapping
from pathlib import Path

from ruamel.yaml import YAML

KUSTOMIZE_PATH = Path("applications/dashboard/helm/kustomize")
OUTPUT_PATH = Path("applications/dashboard/helm/manifests")
DOCUMENTS_DIRECTORY = "documents"
CRD_KIND = "CustomResourceDefinition"
CRD_RETENTION_ANNOTATION = "helm.sh/resource-policy"
KUSTOMIZE_HASH_PATTERN = r"[a-z0-9]{10}"

CRDS_PAYLOAD_FILENAME = "platform-crds.yaml"
RESOURCES_PAYLOAD_FILENAME = "platform-resources.yaml"

GENERATED_HEADER = (
    "# Code generated by scripts/generate-dashboard-helm-manifests.py. "
    "DO NOT EDIT.\n"
    "# Source: kustomize build applications/dashboard/helm/kustomize\n"
    "# Regenerate with: KUBEFLOW_SYNCHRONIZE_NO_COMMIT=true "
    "./scripts/synchronize-dashboard-manifests.sh\n"
)

# Resources rendered by hand-written Helm templates so that the values Kustomize
# already declares - container images and configMapGenerator inputs - can be
# exposed through values.yaml. They are excluded from the generated payloads.
# A prefixed entry matches the content-hash suffix Kustomize appends to
# generated ConfigMap names.
HAND_WRITTEN_RESOURCES = (
    ("Deployment", "dashboard", False),
    ("Deployment", "poddefaults-webhook-deployment", False),
    ("Deployment", "profiles-deployment", False),
    ("ConfigMap", "dashboard-config", False),
    ("ConfigMap", "dashboard-parameters-", True),
    ("ConfigMap", "profiles-config-", True),
    ("ConfigMap", "profiles-namespace-labels-data-", True),
)

# Embedded documents extracted verbatim so a hand-written template can inherit
# the upstream content byte for byte while still allowing an override through
# values.yaml. Written without a generated header because the content must stay
# exactly as upstream produced it.
EXTRACTED_DOCUMENTS = (
    ("ConfigMap", "dashboard-config", False, "links", "dashboard-links.json"),
    ("ConfigMap", "dashboard-config", False, "settings", "dashboard-settings.json"),
    (
        "ConfigMap",
        "profiles-namespace-labels-data-",
        True,
        "namespace-labels.yaml",
        "profile-namespace-labels.yaml",
    ),
)


def resource_identity(resource):
    if not isinstance(resource, Mapping):
        raise ValueError("resource identity requires a YAML mapping")

    api_version = resource.get("apiVersion")
    kind = resource.get("kind")
    metadata = resource.get("metadata")
    if not isinstance(api_version, str) or not api_version:
        raise ValueError("resource identity is missing apiVersion")
    if not isinstance(kind, str) or not kind:
        raise ValueError("resource identity is missing kind")
    if not isinstance(metadata, Mapping):
        raise ValueError("resource identity is missing metadata")

    name = metadata.get("name")
    namespace = metadata.get("namespace", "")
    if not isinstance(name, str) or not name:
        raise ValueError("resource identity is missing metadata.name")
    if not isinstance(namespace, str):
        raise ValueError("resource identity has a non-string metadata.namespace")

    return api_version, kind, namespace, name


def kubernetes_object_identity(resource):
    api_version, kind, namespace, name = resource_identity(resource)
    api_group = api_version.split("/", maxsplit=1)[0] if "/" in api_version else ""
    return api_group, kind, namespace, name


def matches_selector(resource, kind, name, name_is_prefix):
    _, resource_kind, _, resource_name = resource_identity(resource)
    if resource_kind != kind:
        return False
    if not name_is_prefix:
        return resource_name == name
    return (
        re.fullmatch(re.escape(name) + KUSTOMIZE_HASH_PATTERN, resource_name)
        is not None
    )


def parse_resources(rendered_yaml):
    yaml = YAML()
    yaml.allow_duplicate_keys = False
    resources = []
    for document_number, resource in enumerate(yaml.load_all(rendered_yaml), start=1):
        if resource is None:
            continue
        if not isinstance(resource, Mapping):
            raise ValueError(
                f"YAML document {document_number} is not a Kubernetes resource mapping"
            )
        resources.append(resource)
    if not resources:
        raise ValueError("Kustomize rendered no Kubernetes resources")
    return resources


def add_crd_retention(resource):
    retained_resource = copy.deepcopy(resource)
    metadata = retained_resource["metadata"]
    annotations = metadata.get("annotations")
    if annotations is None:
        annotations = {}
        metadata["annotations"] = annotations
    if not isinstance(annotations, Mapping):
        raise ValueError(
            f"CRD {resource_identity(resource)} has non-mapping metadata.annotations"
        )
    annotations[CRD_RETENTION_ANNOTATION] = "keep"
    return retained_resource


def render_payload(resources):
    yaml = YAML()
    yaml.default_flow_style = False
    yaml.explicit_start = True
    yaml.width = 4096
    stream = io.StringIO()
    yaml.dump_all(resources, stream)
    return GENERATED_HEADER + stream.getvalue()


def extract_documents(resource):
    """Return the embedded documents this resource contributes."""
    documents = {}
    for kind, name, name_is_prefix, data_key, filename in EXTRACTED_DOCUMENTS:
        if not matches_selector(resource, kind, name, name_is_prefix):
            continue
        data = resource.get("data")
        if not isinstance(data, Mapping) or data_key not in data:
            raise ValueError(
                f"resource {resource_identity(resource)} is missing "
                f"data key {data_key!r} required for {filename}"
            )
        value = data[data_key]
        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"resource {resource_identity(resource)} has an empty "
                f"data key {data_key!r} required for {filename}"
            )
        documents[f"{DOCUMENTS_DIRECTORY}/{filename}"] = value.rstrip("\n") + "\n"
    return documents


def generate_payload_contents(resources):
    crd_resources = []
    payload_resources = []
    documents = {}
    object_identities = set()
    matched_selectors = {}

    for resource in resources:
        identity = resource_identity(resource)
        object_identity = kubernetes_object_identity(resource)
        if object_identity in object_identities:
            raise ValueError(f"duplicate resource identity: {identity}")
        object_identities.add(object_identity)

        hand_written_selector = next(
            (
                selector
                for selector in HAND_WRITTEN_RESOURCES
                if matches_selector(resource, *selector)
            ),
            None,
        )
        if hand_written_selector is not None:
            if hand_written_selector in matched_selectors:
                raise ValueError(
                    f"resource {identity} matches hand-written selector "
                    f"{hand_written_selector} already matched by "
                    f"{matched_selectors[hand_written_selector]}"
                )
            matched_selectors[hand_written_selector] = identity
            documents.update(extract_documents(resource))
            continue

        if resource["kind"] == CRD_KIND:
            crd_resources.append(add_crd_retention(resource))
        else:
            payload_resources.append(copy.deepcopy(resource))

    unmatched_selectors = [
        selector
        for selector in HAND_WRITTEN_RESOURCES
        if selector not in matched_selectors
    ]
    if unmatched_selectors:
        raise ValueError(
            "hand-written resources are no longer rendered by Kustomize; "
            "their templates are orphaned: "
            + ", ".join(f"{kind}/{name}" for kind, name, _ in unmatched_selectors)
        )

    missing_documents = [
        f"{DOCUMENTS_DIRECTORY}/{filename}"
        for *_, filename in EXTRACTED_DOCUMENTS
        if f"{DOCUMENTS_DIRECTORY}/{filename}" not in documents
    ]
    if missing_documents:
        raise ValueError(
            "required embedded documents were not extracted: "
            + ", ".join(missing_documents)
        )

    empty_payloads = [
        filename
        for filename, entries in (
            (CRDS_PAYLOAD_FILENAME, crd_resources),
            (RESOURCES_PAYLOAD_FILENAME, payload_resources),
        )
        if not entries
    ]
    if empty_payloads:
        raise ValueError(
            "required generated payloads are empty: " + ", ".join(empty_payloads)
        )

    contents = {
        CRDS_PAYLOAD_FILENAME: render_payload(crd_resources),
        RESOURCES_PAYLOAD_FILENAME: render_payload(payload_resources),
    }
    contents.update(documents)
    return contents


def write_payloads_atomically(output_directory, payloads):
    output_directory = Path(output_directory)
    output_directory.parent.mkdir(parents=True, exist_ok=True)
    staging_directory = Path(
        tempfile.mkdtemp(
            prefix=f".{output_directory.name}.new-",
            dir=output_directory.parent,
        )
    )
    backup_directory = output_directory.parent / (
        f".{output_directory.name}.old-{uuid.uuid4().hex}"
    )
    previous_directory_moved = False

    try:
        for filename, contents in payloads.items():
            relative_path = Path(filename)
            if relative_path.is_absolute() or ".." in relative_path.parts:
                raise ValueError(f"payload filename must be relative: {filename}")
            if len(relative_path.parts) > 2:
                raise ValueError(
                    f"payload filename must not nest more than one directory: "
                    f"{filename}"
                )
            if not contents.strip():
                raise ValueError(f"generated payload is empty: {filename}")
            destination = staging_directory / relative_path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(contents, encoding="utf-8", newline="\n")

        if output_directory.exists():
            os.replace(output_directory, backup_directory)
            previous_directory_moved = True

        try:
            os.replace(staging_directory, output_directory)
        except Exception:
            if previous_directory_moved:
                os.replace(backup_directory, output_directory)
                previous_directory_moved = False
            raise

        if previous_directory_moved:
            shutil.rmtree(backup_directory)
            previous_directory_moved = False
    finally:
        if staging_directory.exists():
            shutil.rmtree(staging_directory)
        if previous_directory_moved and backup_directory.exists():
            if not output_directory.exists():
                os.replace(backup_directory, output_directory)


def generate_dashboard_manifests(repository_root):
    repository_root = Path(repository_root).resolve()
    result = subprocess.run(
        ["kustomize", "build", str(KUSTOMIZE_PATH)],
        cwd=repository_root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "Dashboard Kustomize build failed:\n" + result.stderr.rstrip()
        )

    resources = parse_resources(result.stdout)
    payloads = generate_payload_contents(resources)
    write_payloads_atomically(repository_root / OUTPUT_PATH, payloads)
    return len(resources), tuple(payloads)


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Generate component payloads for the Kubeflow Dashboard Helm chart."
    )
    parser.add_argument(
        "--repository-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Path to the kubeflow/community-distribution repository.",
    )
    return parser.parse_args()


def main():
    arguments = parse_arguments()
    try:
        resource_count, payload_filenames = generate_dashboard_manifests(
            arguments.repository_root
        )
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print(
        f"Generated {resource_count} Dashboard resources across "
        f"{len(payload_filenames)} files."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
